## Numpy Arrays

In [2]:
import numpy as np

In [4]:
# List transformed in array
list = [1, 2, 3, 4, 5]
array = np.array(list)
print(array)

[ 3  6  9 12 15]


In [5]:
# Arrays Operations
array = np.array([1, 2, 3, 4, 5])
print(array * 2)
print(array * 3)


[ 2  4  6  8 10]
[ 3  6  9 12 15]


In [10]:
# Matrices Operations
matrix = np.array([[1,2,3] , [4,5,6]])
print(matrix)
print(matrix.shape) # Show the dimensions of the matrix
print(matrix[0, 1]) # Show the element in the first row and second column

[[1 2 3]
 [4 5 6]]
(2, 3)
2


## Exercises

In [ ]:
"""   
Create a program that:

- Asks the user for two numbers and stores them in a NumPy array.
- Multiplies the array by 3 and displays the result.
- Transforms this array into a 2-row matrix and displays the new format.
"""




In [15]:
import numpy as np

# Program that asks the user for two numbers and stores them in a NumPy array
number1 = int(input("Enter the first number: ")) # User input
number2 = int(input("Enter the second number: ")) # User input

array = np.array([number1, number2]) # List transformed in array
print(array * 3) # Array * 3

matrix = np.array([[number1, number2], [number1, number2]]) # Array transformed in matrix
print(matrix) # Show the matrix

[30 60]
[[10 20]
 [10 20]]
